sudo: false
language: node_js
addons:
  chrome: stable
node_js:
- '8'
cache:
  directories:
  - node_modules
  - node_cache
  - node_shrinkwrap
  - $HOME/.npm
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9334 http://localhost &
script:
- npm run test